"""Tests for stage checkpoint and resume engine — Claim R3."""

from __future__ import annotations

from pathlib import Path

from hawedit.checkpoint import (
    clear_stage_checkpoint,
    hash_bytes,
    is_stage_complete,
    load_stage_checkpoint,
    save_stage_checkpoint,
)
from hawedit.ingest import IngestResult


def test_checkpoint_lifecycle(tmp_path: Path) -> None:
    stage = "stage_0_ingest"
    hashes = {
        "source": hash_bytes(b"mock video data"),
        "config": hash_bytes(b"fps=25,proxy=1fps"),
    }

    assert not is_stage_complete(tmp_path, stage, hashes)

    marker = save_stage_checkpoint(
        tmp_path,
        stage,
        hashes,
        metadata={"proxy_path": "proxy.mp4", "duration_s": 48.5},
    )
    assert marker.is_file()
    assert marker.name == "stage_0_ingest.done"

    assert is_stage_complete(tmp_path, stage, hashes)

    loaded = load_stage_checkpoint(tmp_path, stage)
    assert loaded is not None
    assert loaded.stage_name == stage
    assert loaded.input_hashes == hashes
    assert loaded.metadata["duration_s"] == 48.5

    # Altered inputs must fail validation
    altered_hashes = dict(hashes)
    altered_hashes["source"] = hash_bytes(b"different video data")
    assert not is_stage_complete(tmp_path, stage, altered_hashes)

    # Clearing the checkpoint
    cleared = clear_stage_checkpoint(tmp_path, stage)
    assert cleared
    assert not is_stage_complete(tmp_path, stage, hashes)
    assert load_stage_checkpoint(tmp_path, stage) is None


def test_corrupted_checkpoint_fails_gracefully(tmp_path: Path) -> None:
    stage = "stage_1_speech"
    marker = tmp_path / f"{stage}.done"
    marker.write_text("{invalid json truncated", encoding="utf-8")

    assert not is_stage_complete(tmp_path, stage, {"source": "abc"})
    assert load_stage_checkpoint(tmp_path, stage) is None


def test_pipeline_generates_stage_checkpoints(tmp_path: Path) -> None:
    """run_pipeline must write atomic stage checkpoints upon completing stages."""
    from hawedit.pipeline import run_pipeline

    fixture = (
        Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "kurdish-speech-3cuts.mp4"
    )
    work = tmp_path / "work"
    run = run_pipeline(fixture, work)
    assert run is not None
    stage0_marker = work / "stage0_ingest.done"
    assert stage0_marker.is_file(), "stage0_ingest.done was not generated by run_pipeline"
    checkpoint = load_stage_checkpoint(work, "stage0_ingest")
    assert checkpoint is not None
    assert checkpoint.stage_name == "stage0_ingest"
    assert "source_sha256" in checkpoint.input_hashes
    assert (work / "stage0" / "ingest.json").is_file()


def test_pipeline_resumes_stage0_from_checkpoint(tmp_path: Path) -> None:
    """run_pipeline reuses stage0 artifacts when valid checkpoint marker exists."""
    from hawedit.pipeline import run_pipeline

    fixture = (
        Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "kurdish-speech-3cuts.mp4"
    )
    work = tmp_path / "work"
    run1 = run_pipeline(fixture, work)
    assert isinstance(run1.ingest, IngestResult)

    # Re-running into the same work directory resumes Stage 0 from checkpoint
    run2 = run_pipeline(fixture, work)
    assert isinstance(run2.ingest, IngestResult)
    assert run2.ingest.source_sha256 == run1.ingest.source_sha256
    assert run2.ingest.duration_ms == run1.ingest.duration_ms
    assert run2.ingest.shot_cuts_ms == run1.ingest.shot_cuts_ms


def test_pipeline_stage0_corrupted_json_falls_back_safely(tmp_path: Path) -> None:
    """If ingest.json is corrupted, pipeline falls back safely to fresh ingest."""
    from hawedit.pipeline import run_pipeline

    fixture = (
        Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "kurdish-speech-3cuts.mp4"
    )
    work = tmp_path / "work"
    run1 = run_pipeline(fixture, work)
    assert isinstance(run1.ingest, IngestResult)

    # Corrupt the ingest.json file
    ingest_json = work / "stage0" / "ingest.json"
    assert ingest_json.is_file()
    ingest_json.write_text("{invalid json truncated", encoding="utf-8")

    # Pipeline must not crash; it detects corrupted data and re-ingests safely
    run2 = run_pipeline(fixture, work)
    assert isinstance(run2.ingest, IngestResult)
    assert run2.ingest.source_sha256 == run1.ingest.source_sha256
    # And valid json is restored
    assert ingest_json.read_text(encoding="utf-8").startswith("{")
